# Generated by Django 3.1 on 2021-11-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20211128_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='decription',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
