# Generated by Django 3.1 on 2021-12-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_productgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
